workflows:
  android-build:
    name: Build Native Android APK
    max_build_duration: 30
    environment:
      java: 17
    scripts:
      - name: Build APK with Gradle
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
